spring:
  application:
    name: ai-no-code-application
  datasource:
    url: jdbc:mysql://localhost:3306/
    username: root
    password: 12345678
  profiles:
    active: local
server:
  port: 8081
